[package]
name = "pisugar-server"
version = "1.4.8"
authors = ["PiSugar"]
edition = "2018"
description = "PiSugar Power Manager"
license = "GPLv3"

[dependencies]
log = "0.4.8"
env_logger = "0.7"
syslog = "5"
libc = "0.2"
clap = "2"
bytes = "0.5.4"
ctrlc = "3.1.4"
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
tokio = { version = "0.2", features = ["full"] }
tokio-util = "0.2"
tokio-tungstenite = "0.10.1"
futures = "0.3.5"
futures-util = "0.3.5"
futures-channel = "0.3.5"
hyper = "0.13"
hyper-staticfile = "0.5.1"
hyper-websocket-lite = "0.3.4"
websocket-codec = "0.3.5"
pisugar-core = { path = "../pisugar-core" }

[[bin]]
name = "pisugar-server"

[package.metadata.deb]
license-file = ["../LICENSE", "0"]
copyright = "2020, PiSugar team"
extended-description = """\
PiSugar power manager server."""
depends = "$auto, systemd"
section = "utility"
priority = "optional"
maintainer-scripts = "pisugar-server/debian"                                    # working dir relatived
assets = [
    ["target/release/pisugar-server", "usr/bin/", "755"],                       # special
    ["debian/pisugar-server.default", "etc/default/pisugar-server", "644"],
    ["debian/pisugar-server.service", "lib/systemd/system/", "644"],
    ["debian/config.json", "etc/pisugar-server/", "644"],
    ["debian/_ws.json", "usr/share/pisugar-server/web/", "644"],
    #["../electron/dist/web/*", "usr/share/pisugar-server/web/", "644"],
    #["../electron/dist/web/fonts/*", "usr/share/pisugar-server/web/fonts", "644"]
]
conf-files = [
    "/etc/default/pisugar-server",
    "/etc/pisugar-server/config.json"
]

[package.metadata.rpm]
package = "pisugar-server"

[package.metadata.rpm.cargo]
buildflags = ["--release"]

[package.metadata.rpm.targets]
pisugar-server = { path = "/usr/bin/pisugar-server" }

[package.metadata.rpm.files]
"pisugar-server.service" = { path = "/lib/systemd/system/pisugar-server.service" }
"pisugar-server.default" = { path = "/etc/default/pisugar-server" }
"config.json" = { path = "/etc/pisugar-server/config.json" }
"_ws.json" = { path = "/usr/share/pisugar-server/web/_ws.json" }
"../../electron/dist/web/" = { path = "/usr/share/pisugar-server/web" }
